[general]
live_config_reload = true

[window]
padding = { x = 2, y = 2 }
opacity = 0.95
blur = true
title = "Alacritty"

[env]
#TERM = "xterm-256color"

[cursor]
style = { shape = "Block", blinking = "Always" }
blink_interval = 250
blink_timeout = 0

[font]
size = 8

[colors.primary]
background = '#1a1b26'
#foreground = '#a9b1d6'

[colors.normal]
#black =   '#32344a'
#red =     '#f7768e'
#green =   '#9ece6a'
#yellow =  '#e0af68'
#blue =    '#7aa2f7'
#magenta = '#ad8ee6'
#cyan =    '#449dab'
#white =   '#787c99'

[terminal]
#shell = { program = "/bin/bash", args = ["-l"] }
